import 'package:flutter/services.dart';
import '../models/exercise_definition.dart';
import '../services/storage_service.dart';
import '../utils/helpers.dart';

/// Seeds the exercise library with 300+ tagged exercises and a full
/// hierarchical tag tree. Only seeds tags + exercises — no synthetic
/// workout history or measurement data.
class SeedDataService {
  final StorageService _storage;
  SeedDataService(this._storage);

  bool get isLibraryEmpty => _storage.getExercises().isEmpty;

  Future<void> seedLibrary() async {
    print('[SeedData] Seeding exercise library...');
    await _seedTags();
    await _seedExercises();

    print('[SeedData] Seeding programs...');
    await seedPrograms();

    print(
      '[SeedData] Done — ${_storage.getExercises().length} exercises loaded.',
    );
  }

  Future<void> seedPrograms() async {
    final assetFiles = [
      'assets/preloaded_24_week_plan.json',
      'assets/classic_strength_programs.json',
      'assets/classic_programs_b.json',
      'assets/classic_programs_c.json',
      'assets/classic_programs_d.json',
    ];

    for (final assetPath in assetFiles) {
      try {
        final jsonString = await rootBundle.loadString(assetPath);
        final analysis = await _storage.analyzeImport(jsonString);

        if (analysis.isValid) {
          // Automatically prefer local definitions for any exercise conflicts,
          // since the seeded library is the canonical source of truth.
          final Map<String, bool> autoResolution = {};
          for (var conflict in analysis.conflicts) {
            autoResolution[conflict.imported.id] = true;
          }
          await _storage.executeImport(analysis, autoResolution, asCatalogue: true);
          print('[SeedData] Imported $assetPath into catalogue successfully.');
        } else {
          print('[SeedData] Skipping $assetPath — invalid: ${analysis.errorMessage}');
        }
      } catch (e) {
        print('[SeedData] Failed to seed $assetPath: $e');
      }
    }
  }


  Future<void> _seedTags() async {
    final roots = [
      'Upper Body',
      'Lower Body',
      'Core',
      'Full Body',
      'Strength',
      'Hypertrophy',
      'Cardio',
      'Endurance',
      'Bodybuilding',
      'Calisthenics',
      'Yoga',
      'Pilates',
      'Powerlifting',
      'Olympic Lifting',
      'Stretching',
      'Mobility',
      'HIIT',
      'CrossFit',
      'Plyometric',
      'Stability',
      'Rehabilitation',
      'Sport',
      'Functional',
      'Kettlebell',
      'Resistance Bands',
    ];

    final Map<String, String> parents = {
      // Upper Body breakdown
      'Chest': 'Upper Body',
      'Back': 'Upper Body',
      'Shoulders': 'Upper Body',
      'Arms': 'Upper Body',
      // Lower Body breakdown
      'Quadriceps': 'Lower Body',
      'Hamstrings': 'Lower Body',
      'Glutes': 'Lower Body',
      'Calves': 'Lower Body',
      'Hip Flexors': 'Lower Body',
      'Adductors': 'Lower Body',
      'Abductors': 'Lower Body',
      // Core breakdown
      'Abs': 'Core',
      'Obliques': 'Core',
      'Lower Back': 'Core',
      'Transverse Abdominis': 'Core',
      // Arms breakdown
      'Biceps': 'Arms',
      'Triceps': 'Arms',
      'Forearms': 'Arms',
      'Grip': 'Arms',
      // Chest breakdown
      'Upper Chest': 'Chest',
      'Lower Chest': 'Chest',
      'Inner Chest': 'Chest',
      // Back breakdown
      'Lats': 'Back',
      'Upper Traps': 'Back',
      'Lower Traps': 'Back',
      'Rhomboids': 'Back',
      'Teres Major': 'Back',
      // Shoulder breakdown
      'Front Delts': 'Shoulders',
      'Side Delts': 'Shoulders',
      'Rear Delts': 'Shoulders',
      'Rotator Cuff': 'Shoulders',
      // Cardio subtypes
      'Running': 'Cardio',
      'Cycling': 'Cardio',
      'Swimming': 'Cardio',
      'Rowing': 'Cardio',
      'Jump Rope': 'Cardio',
      'Stair Climbing': 'Cardio',
      'Walking': 'Cardio',
      'Boxing': 'Cardio',
      // Calisthenics subtypes
      'Push': 'Calisthenics',
      'Pull': 'Calisthenics',
      'Legs (Calisthenics)': 'Calisthenics',
      'Skill': 'Calisthenics',
      // Yoga subtypes
      'Flexibility': 'Yoga',
      'Balance': 'Yoga',
      'Breathing': 'Yoga',
      'Restorative': 'Yoga',
      'Vinyasa': 'Yoga',
      'Power Yoga': 'Yoga',
      // Pilates subtypes
      'Mat Pilates': 'Pilates',
      'Reformer Pilates': 'Pilates',
      // Powerlifting subtypes
      'Squat': 'Powerlifting',
      'Bench': 'Powerlifting',
      'Deadlift': 'Powerlifting',
      // Olympic Lifting subtypes
      'Snatch': 'Olympic Lifting',
      'Clean & Jerk': 'Olympic Lifting',
      // Stretching subtypes
      'Static Stretch': 'Stretching',
      'Dynamic Stretch': 'Stretching',
      'PNF Stretch': 'Stretching',
      'Foam Rolling': 'Stretching',
    };

    final allTags = <String>{}
      ..addAll(roots)
      ..addAll(parents.keys)
      ..addAll(parents.values);
    await _storage.saveTags(allTags.toList()..sort());
    for (final e in parents.entries) {
      await _storage.saveTagParent(e.key, e.value);
    }
  }

  Future<void> _seedExercises() async {
    final d = <_E>[
      // ── CHEST ──────────────────────────────────────────────────────────
      _E('Barbell Bench Press', [
        'Chest',
        'Upper Chest',
        'Triceps',
        'Front Delts',
        'Strength',
        'Powerlifting',
        'Bench',
        'Bodybuilding',
      ]),
      _E('Incline Barbell Bench Press', [
        'Chest',
        'Upper Chest',
        'Front Delts',
        'Strength',
        'Bodybuilding',
      ]),
      _E('Decline Barbell Bench Press', [
        'Chest',
        'Lower Chest',
        'Triceps',
        'Strength',
        'Bodybuilding',
      ]),
      _E('Dumbbell Bench Press', [
        'Chest',
        'Triceps',
        'Strength',
        'Bodybuilding',
      ]),
      _E('Incline Dumbbell Bench Press', [
        'Chest',
        'Upper Chest',
        'Front Delts',
        'Bodybuilding',
      ]),
      _E('Decline Dumbbell Bench Press', [
        'Chest',
        'Lower Chest',
        'Bodybuilding',
      ]),
      _E('Dumbbell Fly', [
        'Chest',
        'Inner Chest',
        'Hypertrophy',
        'Bodybuilding',
      ]),
      _E('Incline Dumbbell Fly', [
        'Chest',
        'Upper Chest',
        'Hypertrophy',
        'Bodybuilding',
      ]),
      _E('Decline Dumbbell Fly', [
        'Chest',
        'Lower Chest',
        'Hypertrophy',
        'Bodybuilding',
      ]),
      _E('Cable Crossover', [
        'Chest',
        'Inner Chest',
        'Hypertrophy',
        'Bodybuilding',
      ]),
      _E('High-to-Low Cable Fly', ['Chest', 'Lower Chest', 'Bodybuilding']),
      _E('Low-to-High Cable Fly', ['Chest', 'Upper Chest', 'Bodybuilding']),
      _E('Pec Deck Machine', [
        'Chest',
        'Inner Chest',
        'Hypertrophy',
        'Bodybuilding',
      ]),
      _E('Smith Machine Bench Press', [
        'Chest',
        'Upper Chest',
        'Triceps',
        'Bodybuilding',
      ]),
      _E('Landmine Press', ['Chest', 'Upper Chest', 'Shoulders', 'Strength']),
      _E('Push-Up', [
        'Chest',
        'Triceps',
        'Front Delts',
        'Calisthenics',
        'Push',
        'Full Body',
      ]),
      _E('Wide Push-Up', ['Chest', 'Upper Chest', 'Calisthenics', 'Push']),
      _E('Diamond Push-Up', ['Chest', 'Triceps', 'Calisthenics', 'Push']),
      _E('Feet-Elevated Push-Up', [
        'Chest',
        'Upper Chest',
        'Calisthenics',
        'Push',
      ]),
      _E('Archer Push-Up', [
        'Chest',
        'Triceps',
        'Calisthenics',
        'Push',
        'Skill',
      ]),
      _E('Clapping Push-Up', [
        'Chest',
        'Triceps',
        'Calisthenics',
        'Push',
        'Plyometric',
      ]),
      _E('Pseudo Planche Push-Up', [
        'Chest',
        'Front Delts',
        'Calisthenics',
        'Push',
        'Skill',
      ]),
      _E('Chest Dip', [
        'Chest',
        'Lower Chest',
        'Triceps',
        'Calisthenics',
        'Push',
      ]),
      _E('Svend Press', ['Chest', 'Inner Chest', 'Bodybuilding']),
      _E('Chest Press Machine', ['Chest', 'Triceps', 'Bodybuilding']),

      // ── BACK ───────────────────────────────────────────────────────────
      _E('Barbell Row', [
        'Back',
        'Lats',
        'Rhomboids',
        'Biceps',
        'Strength',
        'Bodybuilding',
      ]),
      _E('Pendlay Row', ['Back', 'Lats', 'Rhomboids', 'Strength']),
      _E('Dumbbell Row', ['Back', 'Lats', 'Rhomboids', 'Bodybuilding']),
      _E('Seated Cable Row', [
        'Back',
        'Lats',
        'Rhomboids',
        'Biceps',
        'Bodybuilding',
      ]),
      _E('Wide Grip Lat Pulldown', ['Back', 'Lats', 'Bodybuilding']),
      _E('Close Grip Lat Pulldown', ['Back', 'Lats', 'Biceps', 'Bodybuilding']),
      _E('Reverse Grip Lat Pulldown', [
        'Back',
        'Lats',
        'Biceps',
        'Bodybuilding',
      ]),
      _E('Pull-Up', [
        'Back',
        'Lats',
        'Biceps',
        'Calisthenics',
        'Pull',
        'Full Body',
      ]),
      _E('Chin-Up', ['Back', 'Lats', 'Biceps', 'Calisthenics', 'Pull']),
      _E('Neutral Grip Pull-Up', [
        'Back',
        'Lats',
        'Biceps',
        'Calisthenics',
        'Pull',
      ]),
      _E('Wide Grip Pull-Up', ['Back', 'Lats', 'Calisthenics', 'Pull']),
      _E('Commando Pull-Up', [
        'Back',
        'Lats',
        'Biceps',
        'Calisthenics',
        'Pull',
        'Skill',
      ]),
      _E('Muscle-Up', [
        'Back',
        'Chest',
        'Triceps',
        'Calisthenics',
        'Pull',
        'Push',
        'Skill',
      ]),
      _E('Assisted Pull-Up', [
        'Back',
        'Lats',
        'Biceps',
        'Calisthenics',
        'Pull',
      ]),
      _E('Deadlift', [
        'Back',
        'Lower Back',
        'Hamstrings',
        'Glutes',
        'Strength',
        'Powerlifting',
        'Deadlift',
        'Full Body',
      ]),
      _E('Romanian Deadlift', [
        'Back',
        'Lower Back',
        'Hamstrings',
        'Glutes',
        'Strength',
        'Bodybuilding',
      ]),
      _E('Sumo Deadlift', [
        'Back',
        'Lower Back',
        'Glutes',
        'Adductors',
        'Strength',
        'Powerlifting',
      ]),
      _E('Trap Bar Deadlift', [
        'Back',
        'Lower Back',
        'Quadriceps',
        'Glutes',
        'Strength',
      ]),
      _E('Single Leg Romanian Deadlift', [
        'Back',
        'Hamstrings',
        'Glutes',
        'Stability',
        'Bodybuilding',
      ]),
      _E('Hyperextension', ['Lower Back', 'Glutes', 'Hamstrings', 'Core']),
      _E('Good Morning', ['Lower Back', 'Hamstrings', 'Glutes', 'Strength']),
      _E('T-Bar Row', ['Back', 'Lats', 'Rhomboids', 'Bodybuilding']),
      _E('Single Arm Cable Row', ['Back', 'Lats', 'Rhomboids', 'Bodybuilding']),
      _E('Face Pull', [
        'Rear Delts',
        'Rhomboids',
        'Rotator Cuff',
        'Bodybuilding',
      ]),
      _E('Straight Arm Pulldown', ['Back', 'Lats', 'Bodybuilding']),
      _E('Inverted Row', ['Back', 'Lats', 'Biceps', 'Calisthenics', 'Pull']),
      _E('Australian Pull-Up', [
        'Back',
        'Lats',
        'Biceps',
        'Calisthenics',
        'Pull',
      ]),
      _E('Rack Pull', [
        'Back',
        'Lower Back',
        'Glutes',
        'Hamstrings',
        'Strength',
      ]),
      _E('Meadows Row', ['Back', 'Lats', 'Rhomboids', 'Bodybuilding']),
      _E('Cable Pullover', ['Back', 'Lats', 'Bodybuilding']),
      _E('Dumbbell Pullover', ['Back', 'Lats', 'Chest', 'Bodybuilding']),
      _E('Back Extension Machine', ['Lower Back', 'Glutes', 'Bodybuilding']),

      // ── SHOULDERS ─────────────────────────────────────────────────────
      _E('Barbell Overhead Press', [
        'Shoulders',
        'Front Delts',
        'Triceps',
        'Strength',
        'Bodybuilding',
      ]),
      _E('Seated Barbell Overhead Press', [
        'Shoulders',
        'Front Delts',
        'Triceps',
        'Bodybuilding',
      ]),
      _E('Dumbbell Overhead Press', [
        'Shoulders',
        'Front Delts',
        'Side Delts',
        'Bodybuilding',
      ]),
      _E('Arnold Press', [
        'Shoulders',
        'Front Delts',
        'Side Delts',
        'Rear Delts',
        'Bodybuilding',
      ]),
      _E('Lateral Raise', ['Shoulders', 'Side Delts', 'Bodybuilding']),
      _E('Cable Lateral Raise', ['Shoulders', 'Side Delts', 'Bodybuilding']),
      _E('Machine Lateral Raise', ['Shoulders', 'Side Delts', 'Bodybuilding']),
      _E('Front Raise', ['Shoulders', 'Front Delts', 'Bodybuilding']),
      _E('Cable Front Raise', ['Shoulders', 'Front Delts', 'Bodybuilding']),
      _E('Rear Delt Fly', [
        'Shoulders',
        'Rear Delts',
        'Rhomboids',
        'Bodybuilding',
      ]),
      _E('Reverse Pec Deck', [
        'Shoulders',
        'Rear Delts',
        'Rhomboids',
        'Bodybuilding',
      ]),
      _E('Cable Rear Delt Fly', ['Shoulders', 'Rear Delts', 'Bodybuilding']),
      _E('Machine Shoulder Press', [
        'Shoulders',
        'Front Delts',
        'Bodybuilding',
      ]),
      _E('Upright Row', [
        'Shoulders',
        'Upper Traps',
        'Side Delts',
        'Bodybuilding',
      ]),
      _E('Shrug', ['Upper Traps', 'Strength', 'Bodybuilding']),
      _E('Dumbbell Shrug', ['Upper Traps', 'Bodybuilding']),
      _E('Behind-the-Neck Press', [
        'Shoulders',
        'Side Delts',
        'Rear Delts',
        'Bodybuilding',
      ]),
      _E('Band Pull-Apart', [
        'Rear Delts',
        'Rhomboids',
        'Rotator Cuff',
        'Mobility',
      ]),
      _E('External Rotation', ['Rotator Cuff', 'Mobility', 'Stretching']),
      _E('Internal Rotation', ['Rotator Cuff', 'Mobility', 'Rehabilitation']),
      _E('Push Press', [
        'Shoulders',
        'Front Delts',
        'Triceps',
        'Strength',
        'Olympic Lifting',
      ]),
      _E('Pike Push-Up', [
        'Shoulders',
        'Front Delts',
        'Triceps',
        'Calisthenics',
        'Push',
      ]),
      _E('Handstand Push-Up', [
        'Shoulders',
        'Front Delts',
        'Triceps',
        'Calisthenics',
        'Push',
        'Skill',
      ]),
      _E('Handstand Hold', [
        'Shoulders',
        'Core',
        'Calisthenics',
        'Skill',
        'Balance',
      ]),

      // ── BICEPS ────────────────────────────────────────────────────────
      _E('Barbell Curl', ['Arms', 'Biceps', 'Bodybuilding', 'Hypertrophy']),
      _E('EZ Bar Curl', ['Arms', 'Biceps', 'Bodybuilding']),
      _E('Dumbbell Curl', ['Arms', 'Biceps', 'Bodybuilding', 'Hypertrophy']),
      _E('Alternating Dumbbell Curl', ['Arms', 'Biceps', 'Bodybuilding']),
      _E('Hammer Curl', ['Arms', 'Biceps', 'Forearms', 'Bodybuilding']),
      _E('Cross-Body Hammer Curl', [
        'Arms',
        'Biceps',
        'Forearms',
        'Bodybuilding',
      ]),
      _E('Incline Dumbbell Curl', ['Arms', 'Biceps', 'Bodybuilding']),
      _E('Concentration Curl', ['Arms', 'Biceps', 'Bodybuilding']),
      _E('Preacher Curl', ['Arms', 'Biceps', 'Bodybuilding']),
      _E('Cable Curl', ['Arms', 'Biceps', 'Bodybuilding']),
      _E('High Cable Curl', ['Arms', 'Biceps', 'Bodybuilding']),
      _E('Reverse Curl', ['Arms', 'Biceps', 'Forearms', 'Bodybuilding']),
      _E('Spider Curl', ['Arms', 'Biceps', 'Bodybuilding']),
      _E('21s Curl', ['Arms', 'Biceps', 'Hypertrophy']),
      _E('Zottman Curl', ['Arms', 'Biceps', 'Forearms', 'Bodybuilding']),
      _E('Machine Curl', ['Arms', 'Biceps', 'Bodybuilding']),

      // ── TRICEPS ───────────────────────────────────────────────────────
      _E('Skull Crusher', ['Arms', 'Triceps', 'Bodybuilding', 'Hypertrophy']),
      _E('Triceps Pushdown', ['Arms', 'Triceps', 'Bodybuilding']),
      _E('Rope Pushdown', ['Arms', 'Triceps', 'Bodybuilding']),
      _E('Reverse Grip Pushdown', ['Arms', 'Triceps', 'Bodybuilding']),
      _E('Overhead Triceps Extension', ['Arms', 'Triceps', 'Bodybuilding']),
      _E('Cable Overhead Triceps Extension', [
        'Arms',
        'Triceps',
        'Bodybuilding',
      ]),
      _E('Close Grip Bench Press', ['Arms', 'Triceps', 'Chest', 'Strength']),
      _E('Triceps Dip', ['Arms', 'Triceps', 'Chest', 'Calisthenics', 'Push']),
      _E('Bench Dip', ['Arms', 'Triceps', 'Calisthenics', 'Push']),
      _E('Kickback', ['Arms', 'Triceps', 'Bodybuilding']),
      _E('JM Press', ['Arms', 'Triceps', 'Chest', 'Strength']),
      _E('Tate Press', ['Arms', 'Triceps', 'Bodybuilding']),

      // ── FOREARMS / GRIP ───────────────────────────────────────────────
      _E('Wrist Curl', ['Arms', 'Forearms', 'Hypertrophy']),
      _E('Reverse Wrist Curl', ['Arms', 'Forearms', 'Hypertrophy']),
      _E('Farmer Carry', [
        'Arms',
        'Forearms',
        'Grip',
        'Strength',
        'Full Body',
        'Functional',
      ]),
      _E('Plate Pinch', ['Arms', 'Forearms', 'Grip', 'Strength']),
      _E('Dead Hang', [
        'Arms',
        'Forearms',
        'Grip',
        'Back',
        'Calisthenics',
        'Mobility',
      ]),
      _E('Towel Pull-Up', [
        'Arms',
        'Forearms',
        'Grip',
        'Back',
        'Calisthenics',
        'Pull',
      ]),
      _E('Rope Climb', [
        'Arms',
        'Forearms',
        'Grip',
        'Back',
        'Biceps',
        'Calisthenics',
        'Pull',
        'Skill',
      ]),

      // ── QUADRICEPS ────────────────────────────────────────────────────
      _E('Barbell Back Squat', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Strength',
        'Powerlifting',
        'Squat',
        'Full Body',
      ]),
      _E('Front Squat', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Strength',
        'Olympic Lifting',
      ]),
      _E('Goblet Squat', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Strength',
        'Functional',
      ]),
      _E('Zercher Squat', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Core',
        'Strength',
      ]),
      _E('Hack Squat', ['Lower Body', 'Quadriceps', 'Glutes', 'Bodybuilding']),
      _E('Leg Press', ['Lower Body', 'Quadriceps', 'Glutes', 'Bodybuilding']),
      _E('Leg Extension', [
        'Lower Body',
        'Quadriceps',
        'Bodybuilding',
        'Hypertrophy',
      ]),
      _E('Sissy Squat', ['Lower Body', 'Quadriceps', 'Calisthenics']),
      _E('Bulgarian Split Squat', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Hamstrings',
        'Bodybuilding',
      ]),
      _E('Lunge', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Bodybuilding',
        'Full Body',
      ]),
      _E('Walking Lunge', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Full Body',
        'Functional',
      ]),
      _E('Reverse Lunge', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Bodybuilding',
      ]),
      _E('Lateral Lunge', [
        'Lower Body',
        'Quadriceps',
        'Adductors',
        'Abductors',
        'Functional',
      ]),
      _E('Step Up', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Bodybuilding',
        'Functional',
      ]),
      _E('Pistol Squat', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Calisthenics',
        'Skill',
        'Balance',
      ]),
      _E('Box Squat', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Strength',
        'Powerlifting',
      ]),
      _E('Pause Squat', ['Lower Body', 'Quadriceps', 'Glutes', 'Strength']),
      _E('Spanish Squat', [
        'Lower Body',
        'Quadriceps',
        'Rehabilitation',
        'Mobility',
      ]),
      _E('Smith Machine Squat', [
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Bodybuilding',
      ]),
      _E('Bodyweight Jump Squat', [
        'Lower Body',
        'Quadriceps',
        'Plyometric',
        'Calisthenics',
      ]),
      _E('Bodyweight Split Squat', [
        'Lower Body',
        'Quadriceps',
        'Calisthenics',
      ]),

      // ── HAMSTRINGS ────────────────────────────────────────────────────
      _E('Leg Curl', [
        'Lower Body',
        'Hamstrings',
        'Bodybuilding',
        'Hypertrophy',
      ]),
      _E('Seated Leg Curl', ['Lower Body', 'Hamstrings', 'Bodybuilding']),
      _E('Nordic Curl', [
        'Lower Body',
        'Hamstrings',
        'Calisthenics',
        'Strength',
      ]),
      _E('Stiff Leg Deadlift', [
        'Lower Body',
        'Hamstrings',
        'Lower Back',
        'Strength',
      ]),
      _E('Glute Ham Raise', ['Lower Body', 'Hamstrings', 'Glutes', 'Strength']),
      _E('Lying Leg Curl', ['Lower Body', 'Hamstrings', 'Bodybuilding']),
      _E('Single Leg Curl', ['Lower Body', 'Hamstrings', 'Bodybuilding']),

      // ── GLUTES ────────────────────────────────────────────────────────
      _E('Hip Thrust', [
        'Lower Body',
        'Glutes',
        'Hamstrings',
        'Bodybuilding',
        'Strength',
      ]),
      _E('Barbell Hip Thrust', [
        'Lower Body',
        'Glutes',
        'Hamstrings',
        'Bodybuilding',
        'Strength',
      ]),
      _E('Glute Bridge', [
        'Lower Body',
        'Glutes',
        'Bodybuilding',
        'Rehabilitation',
      ]),
      _E('Single Leg Glute Bridge', [
        'Lower Body',
        'Glutes',
        'Stability',
        'Rehabilitation',
      ]),
      _E('Cable Kickback', ['Lower Body', 'Glutes', 'Bodybuilding']),
      _E('Sumo Squat', [
        'Lower Body',
        'Glutes',
        'Quadriceps',
        'Adductors',
        'Strength',
      ]),
      _E('Fire Hydrant', ['Lower Body', 'Glutes', 'Abductors', 'Calisthenics']),
      _E('Clamshell', ['Lower Body', 'Glutes', 'Abductors', 'Rehabilitation']),
      _E('Donkey Kicks', ['Lower Body', 'Glutes', 'Calisthenics']),
      _E('Single Leg Hip Thrust', ['Lower Body', 'Glutes', 'Bodybuilding']),
      _E('Sumo Deadlift High Pull', [
        'Lower Body',
        'Glutes',
        'Hamstrings',
        'Shoulders',
        'CrossFit',
      ]),

      // ── CALVES ────────────────────────────────────────────────────────
      _E('Standing Calf Raise', ['Lower Body', 'Calves', 'Bodybuilding']),
      _E('Seated Calf Raise', ['Lower Body', 'Calves', 'Bodybuilding']),
      _E('Donkey Calf Raise', ['Lower Body', 'Calves', 'Bodybuilding']),
      _E('Single Leg Calf Raise', [
        'Lower Body',
        'Calves',
        'Bodybuilding',
        'Stability',
      ]),
      _E('Tibialis Raise', ['Lower Body', 'Calves', 'Rehabilitation']),
      _E('Jump Rope', ['Cardio', 'Jump Rope', 'Calves', 'Endurance', 'HIIT']),

      // ── CORE ──────────────────────────────────────────────────────────
      _E('Plank', ['Core', 'Abs', 'Full Body', 'Calisthenics', 'Stability']),
      _E('Side Plank', ['Core', 'Obliques', 'Calisthenics', 'Stability']),
      _E('Plank Up-Down', ['Core', 'Abs', 'Triceps', 'Calisthenics']),
      _E('Plank Shoulder Tap', ['Core', 'Abs', 'Stability', 'Calisthenics']),
      _E('Copenhagen Plank', ['Core', 'Adductors', 'Obliques', 'Stability']),
      _E('Crunch', ['Core', 'Abs', 'Calisthenics']),
      _E('Bicycle Crunch', ['Core', 'Abs', 'Obliques', 'Calisthenics']),
      _E('Reverse Crunch', ['Core', 'Abs', 'Hip Flexors', 'Calisthenics']),
      _E('Leg Raise', ['Core', 'Abs', 'Hip Flexors', 'Calisthenics']),
      _E('Hanging Leg Raise', ['Core', 'Abs', 'Hip Flexors', 'Calisthenics']),
      _E('Hanging Knee Raise', ['Core', 'Abs', 'Hip Flexors', 'Calisthenics']),
      _E('Toes to Bar', [
        'Core',
        'Abs',
        'Hip Flexors',
        'Calisthenics',
        'CrossFit',
      ]),
      _E('Russian Twist', ['Core', 'Abs', 'Obliques', 'Calisthenics']),
      _E('Ab Wheel Rollout', ['Core', 'Abs', 'Calisthenics', 'Strength']),
      _E('Cable Crunch', ['Core', 'Abs', 'Bodybuilding']),
      _E('Decline Crunch', ['Core', 'Abs', 'Calisthenics']),
      _E('V-Up', ['Core', 'Abs', 'Hip Flexors', 'Calisthenics']),
      _E('Hollow Body Hold', ['Core', 'Abs', 'Calisthenics', 'Skill']),
      _E('L-Sit', [
        'Core',
        'Abs',
        'Hip Flexors',
        'Triceps',
        'Calisthenics',
        'Skill',
      ]),
      _E('Mountain Climber', ['Core', 'Abs', 'Cardio', 'HIIT', 'Calisthenics']),
      _E('Dragon Flag', ['Core', 'Abs', 'Calisthenics', 'Strength', 'Skill']),
      _E('Dead Bug', [
        'Core',
        'Abs',
        'Lower Back',
        'Stability',
        'Rehabilitation',
      ]),
      _E('Bird Dog', [
        'Core',
        'Lower Back',
        'Stability',
        'Calisthenics',
        'Rehabilitation',
      ]),
      _E('Woodchop', ['Core', 'Obliques', 'Strength', 'Functional']),
      _E('Pallof Press', [
        'Core',
        'Transverse Abdominis',
        'Obliques',
        'Stability',
        'Functional',
      ]),
      _E('Suitcase Carry', [
        'Core',
        'Obliques',
        'Forearms',
        'Grip',
        'Functional',
      ]),
      _E('GHD Sit-Up', ['Core', 'Abs', 'Hip Flexors', 'CrossFit']),
      _E('Toe Touch Crunch', ['Core', 'Abs', 'Calisthenics']),
      _E('Flutter Kick', ['Core', 'Abs', 'Hip Flexors', 'Calisthenics']),

      // ── CARDIO ────────────────────────────────────────────────────────
      _E('Treadmill Run', ['Cardio', 'Running', 'Endurance']),
      _E('Outdoor Run', ['Cardio', 'Running', 'Endurance']),
      _E('Sprint Intervals', ['Cardio', 'Running', 'HIIT', 'Endurance']),
      _E('Hill Run', ['Cardio', 'Running', 'Endurance', 'Lower Body']),
      _E('Stationary Bike', ['Cardio', 'Cycling', 'Endurance', 'Lower Body']),
      _E('Outdoor Cycling', ['Cardio', 'Cycling', 'Endurance', 'Lower Body']),
      _E('Spin Class', ['Cardio', 'Cycling', 'HIIT', 'Endurance']),
      _E('Rowing Machine', ['Cardio', 'Rowing', 'Full Body', 'Endurance']),
      _E('Outdoor Rowing', ['Cardio', 'Rowing', 'Full Body', 'Endurance']),
      _E('Elliptical', ['Cardio', 'Endurance', 'Lower Body']),
      _E('Stair Climber', [
        'Cardio',
        'Stair Climbing',
        'Lower Body',
        'Endurance',
      ]),
      _E('Battle Ropes', ['Cardio', 'HIIT', 'Upper Body', 'Full Body']),
      _E('Burpee', ['Cardio', 'HIIT', 'Full Body', 'Calisthenics']),
      _E('Box Jump', ['Cardio', 'HIIT', 'Lower Body', 'Plyometric']),
      _E('Broad Jump', ['Cardio', 'Plyometric', 'Lower Body', 'Full Body']),
      _E('Depth Jump', ['Cardio', 'Plyometric', 'Lower Body', 'Quadriceps']),
      _E('Jumping Jacks', [
        'Cardio',
        'HIIT',
        'Full Body',
        'Calisthenics',
        'Endurance',
      ]),
      _E('High Knees', [
        'Cardio',
        'HIIT',
        'Running',
        'Calisthenics',
        'Hip Flexors',
      ]),
      _E('Butt Kicks', ['Cardio', 'HIIT', 'Hamstrings', 'Calisthenics']),
      _E('Lateral Shuffle', [
        'Cardio',
        'HIIT',
        'Agility',
        'Sport',
        'Lower Body',
      ]),
      _E('Bear Crawl', [
        'Cardio',
        'Full Body',
        'Calisthenics',
        'Core',
        'Functional',
      ]),
      _E('Crab Walk', ['Cardio', 'Full Body', 'Calisthenics', 'Triceps']),
      _E('Swimming Freestyle', [
        'Cardio',
        'Swimming',
        'Full Body',
        'Endurance',
      ]),
      _E('Swimming Backstroke', ['Cardio', 'Swimming', 'Back', 'Endurance']),
      _E('Swimming Breaststroke', [
        'Cardio',
        'Swimming',
        'Chest',
        'Full Body',
        'Endurance',
      ]),
      _E('Swimming Butterfly', [
        'Cardio',
        'Swimming',
        'Full Body',
        'Endurance',
      ]),
      _E('Shadow Boxing', [
        'Cardio',
        'Boxing',
        'HIIT',
        'Upper Body',
        'Endurance',
      ]),
      _E('Heavy Bag', ['Cardio', 'Boxing', 'HIIT', 'Upper Body', 'Full Body']),
      _E('Speed Bag', ['Cardio', 'Boxing', 'HIIT', 'Shoulders', 'Endurance']),
      _E('Agility Ladder', [
        'Cardio',
        'Sport',
        'Agility',
        'HIIT',
        'Legs (Calisthenics)',
      ]),
      _E('Incline Walk', ['Cardio', 'Walking', 'Endurance', 'Lower Body']),
      _E('Sled Push', [
        'Cardio',
        'Full Body',
        'Quadriceps',
        'Glutes',
        'Strength',
      ]),
      _E('Sled Pull', [
        'Cardio',
        'Full Body',
        'Hamstrings',
        'Glutes',
        'Strength',
      ]),
      _E('Zone 2 Run/Bike', ['Cardio', 'Endurance', 'Running', 'Cycling']),
      _E('Zone 2 Long Run', ['Cardio', 'Endurance', 'Running']),
      _E('Easy Run', ['Cardio', 'Endurance', 'Running']),
      _E('Running Strides', ['Cardio', 'Running', 'Speed', 'HIIT']),
      _E('Track Intervals', ['Cardio', 'Running', 'Speed', 'HIIT']),
      _E('Tempo Run', ['Cardio', 'Endurance', 'Running']),

      // ── OLYMPIC / POWER ───────────────────────────────────────────────
      _E('Power Clean', [
        'Olympic Lifting',
        'Clean & Jerk',
        'Full Body',
        'Strength',
      ]),
      _E('Hang Clean', [
        'Olympic Lifting',
        'Clean & Jerk',
        'Full Body',
        'Strength',
      ]),
      _E('Power Snatch', [
        'Olympic Lifting',
        'Snatch',
        'Full Body',
        'Strength',
      ]),
      _E('Hang Snatch', ['Olympic Lifting', 'Snatch', 'Full Body', 'Strength']),
      _E('Clean and Jerk', [
        'Olympic Lifting',
        'Clean & Jerk',
        'Full Body',
        'Strength',
      ]),
      _E('Overhead Squat', [
        'Olympic Lifting',
        'Snatch',
        'Quadriceps',
        'Shoulders',
        'Mobility',
      ]),
      _E('Kettlebell Swing', [
        'Kettlebell',
        'Full Body',
        'Glutes',
        'Hamstrings',
        'Strength',
        'Cardio',
      ]),
      _E('Kettlebell Goblet Squat', [
        'Kettlebell',
        'Quadriceps',
        'Glutes',
        'Functional',
      ]),
      _E('Kettlebell Clean', [
        'Kettlebell',
        'Full Body',
        'Strength',
        'Olympic Lifting',
      ]),
      _E('Kettlebell Snatch', [
        'Kettlebell',
        'Full Body',
        'Strength',
        'Olympic Lifting',
      ]),
      _E('Kettlebell Press', [
        'Kettlebell',
        'Shoulders',
        'Triceps',
        'Strength',
      ]),
      _E('Kettlebell Row', ['Kettlebell', 'Back', 'Biceps', 'Strength']),
      _E('Kettlebell Turkish Get-Up', [
        'Kettlebell',
        'Full Body',
        'Stability',
        'Strength',
        'Functional',
      ]),
      _E('Kettlebell Windmill', [
        'Kettlebell',
        'Core',
        'Obliques',
        'Shoulders',
        'Mobility',
      ]),
      _E('Kettlebell Figure 8', [
        'Kettlebell',
        'Core',
        'Forearms',
        'Functional',
      ]),
      _E('Thruster', [
        'Olympic Lifting',
        'Full Body',
        'Shoulders',
        'Quadriceps',
        'CrossFit',
      ]),
      _E('Wall Ball', [
        'CrossFit',
        'Full Body',
        'Quadriceps',
        'Shoulders',
        'Cardio',
      ]),
      _E('Clean Pull', ['Olympic Lifting', 'Full Body', 'Strength']),
      _E('Push Jerk', [
        'Olympic Lifting',
        'Shoulders',
        'Full Body',
        'Strength',
      ]),

      // ── CALISTHENICS SKILL ────────────────────────────────────────────
      _E('Front Lever', [
        'Calisthenics',
        'Back',
        'Lats',
        'Core',
        'Abs',
        'Skill',
      ]),
      _E('Back Lever', ['Calisthenics', 'Back', 'Chest', 'Biceps', 'Skill']),
      _E('Planche', [
        'Calisthenics',
        'Chest',
        'Front Delts',
        'Triceps',
        'Skill',
      ]),
      _E('Planche Lean', [
        'Calisthenics',
        'Chest',
        'Front Delts',
        'Core',
        'Skill',
      ]),
      _E('Human Flag', [
        'Calisthenics',
        'Core',
        'Obliques',
        'Shoulders',
        'Skill',
      ]),
      _E('Ring Dip', ['Calisthenics', 'Chest', 'Triceps', 'Push', 'Skill']),
      _E('Ring Row', ['Calisthenics', 'Back', 'Biceps', 'Pull', 'Skill']),
      _E('Ring Push-Up', [
        'Calisthenics',
        'Chest',
        'Triceps',
        'Push',
        'Stability',
      ]),
      _E('Ring Muscle-Up', [
        'Calisthenics',
        'Back',
        'Chest',
        'Triceps',
        'Biceps',
        'Skill',
      ]),
      _E('Bar Muscle-Up', ['Calisthenics', 'Back', 'Chest', 'Skill']),
      _E('Typewriter Pull-Up', [
        'Calisthenics',
        'Back',
        'Lats',
        'Biceps',
        'Pull',
        'Skill',
      ]),
      _E('Skin the Cat', [
        'Calisthenics',
        'Back',
        'Shoulders',
        'Flexibility',
        'Skill',
      ]),

      // ── YOGA POSES ────────────────────────────────────────────────────
      _E('Downward Dog', [
        'Yoga',
        'Flexibility',
        'Stretching',
        'Full Body',
        'Mobility',
      ]),
      _E('Upward Facing Dog', [
        'Yoga',
        'Flexibility',
        'Chest',
        'Lower Back',
        'Stretching',
      ]),
      _E('Warrior I', [
        'Yoga',
        'Balance',
        'Flexibility',
        'Quadriceps',
        'Stretching',
      ]),
      _E('Warrior II', [
        'Yoga',
        'Balance',
        'Flexibility',
        'Quadriceps',
        'Adductors',
      ]),
      _E('Warrior III', ['Yoga', 'Balance', 'Glutes', 'Hamstrings', 'Core']),
      _E('Reverse Warrior', ['Yoga', 'Flexibility', 'Side Delts', 'Obliques']),
      _E('Triangle Pose', [
        'Yoga',
        'Flexibility',
        'Hamstrings',
        'Obliques',
        'Balance',
      ]),
      _E('Extended Side Angle', [
        'Yoga',
        'Flexibility',
        'Adductors',
        'Obliques',
      ]),
      _E('Child\'s Pose', [
        'Yoga',
        'Restorative',
        'Flexibility',
        'Lower Back',
        'Hip Flexors',
      ]),
      _E('Pigeon Pose', [
        'Yoga',
        'Flexibility',
        'Hip Flexors',
        'Glutes',
        'Stretching',
      ]),
      _E('Sleeping Pigeon', [
        'Yoga',
        'Restorative',
        'Hip Flexors',
        'Glutes',
        'Flexibility',
      ]),
      _E('Sun Salutation A', [
        'Yoga',
        'Vinyasa',
        'Flexibility',
        'Breathing',
        'Full Body',
      ]),
      _E('Sun Salutation B', [
        'Yoga',
        'Vinyasa',
        'Flexibility',
        'Full Body',
        'Strength',
      ]),
      _E('Cat-Cow Stretch', [
        'Yoga',
        'Flexibility',
        'Lower Back',
        'Mobility',
        'Rehabilitation',
      ]),
      _E('Cobra Pose', [
        'Yoga',
        'Flexibility',
        'Chest',
        'Lower Back',
        'Stretching',
      ]),
      _E('Sphinx Pose', [
        'Yoga',
        'Restorative',
        'Lower Back',
        'Chest',
        'Flexibility',
      ]),
      _E('Seated Forward Fold', [
        'Yoga',
        'Flexibility',
        'Hamstrings',
        'Lower Back',
        'Stretching',
      ]),
      _E('Standing Forward Fold', [
        'Yoga',
        'Flexibility',
        'Hamstrings',
        'Lower Back',
      ]),
      _E('Half Moon Pose', [
        'Yoga',
        'Balance',
        'Core',
        'Hamstrings',
        'Abductors',
      ]),
      _E('Mountain Pose', ['Yoga', 'Balance', 'Posture', 'Full Body']),
      _E('Chair Pose', ['Yoga', 'Quadriceps', 'Glutes', 'Balance', 'Strength']),
      _E('Tree Pose', ['Yoga', 'Balance', 'Glutes', 'Abductors', 'Core']),
      _E('Eagle Pose', [
        'Yoga',
        'Balance',
        'Shoulders',
        'Adductors',
        'Flexibility',
      ]),
      _E('Boat Pose', ['Yoga', 'Core', 'Abs', 'Hip Flexors', 'Balance']),
      _E('Crow Pose', ['Yoga', 'Balance', 'Core', 'Triceps', 'Skill']),
      _E('Headstand', ['Yoga', 'Balance', 'Shoulders', 'Core', 'Skill']),
      _E('Shoulder Stand', [
        'Yoga',
        'Balance',
        'Shoulders',
        'Core',
        'Flexibility',
      ]),
      _E('Plow Pose', ['Yoga', 'Flexibility', 'Lower Back', 'Hamstrings']),
      _E('Bridge Pose', [
        'Yoga',
        'Flexibility',
        'Glutes',
        'Chest',
        'Lower Back',
      ]),
      _E('Wheel Pose', [
        'Yoga',
        'Flexibility',
        'Power Yoga',
        'Chest',
        'Lower Back',
        'Shoulders',
      ]),
      _E('Seated Spinal Twist', [
        'Yoga',
        'Flexibility',
        'Obliques',
        'Lower Back',
        'Stretching',
      ]),
      _E('Supine Twist', [
        'Yoga',
        'Restorative',
        'Lower Back',
        'Obliques',
        'Flexibility',
      ]),
      _E('Happy Baby Pose', [
        'Yoga',
        'Restorative',
        'Hip Flexors',
        'Glutes',
        'Lower Back',
      ]),
      _E('Legs Up the Wall', [
        'Yoga',
        'Restorative',
        'Calves',
        'Lower Back',
        'Recovery',
      ]),
      _E('Corpse Pose', ['Yoga', 'Restorative', 'Breathing', 'Flexibility']),
      _E('Camel Pose', [
        'Yoga',
        'Flexibility',
        'Chest',
        'Lower Back',
        'Hip Flexors',
      ]),
      _E('Fish Pose', [
        'Yoga',
        'Flexibility',
        'Chest',
        'Upper Traps',
        'Breathing',
      ]),
      _E('Low Lunge', [
        'Yoga',
        'Flexibility',
        'Hip Flexors',
        'Quadriceps',
        'Stretching',
      ]),
      _E('Lizard Pose', [
        'Yoga',
        'Flexibility',
        'Hip Flexors',
        'Adductors',
        'Stretching',
      ]),
      _E('Half Splits', [
        'Yoga',
        'Flexibility',
        'Hamstrings',
        'Hip Flexors',
        'Stretching',
      ]),
      _E('Full Splits', [
        'Yoga',
        'Flexibility',
        'Hamstrings',
        'Hip Flexors',
        'Adductors',
        'Skill',
      ]),
      _E('Wide-Legged Forward Fold', [
        'Yoga',
        'Flexibility',
        'Adductors',
        'Hamstrings',
        'Lower Back',
      ]),
      _E('Bound Angle Pose', [
        'Yoga',
        'Flexibility',
        'Adductors',
        'Hip Flexors',
        'Restorative',
      ]),
      _E('Firefly Pose', [
        'Yoga',
        'Balance',
        'Core',
        'Hamstrings',
        'Triceps',
        'Skill',
      ]),
      _E('Side Crow', [
        'Yoga',
        'Balance',
        'Core',
        'Obliques',
        'Triceps',
        'Skill',
      ]),

      // ── PILATES ───────────────────────────────────────────────────────
      _E('The Hundred', ['Pilates', 'Mat Pilates', 'Core', 'Abs', 'Endurance']),
      _E('Roll Up', ['Pilates', 'Mat Pilates', 'Core', 'Abs', 'Flexibility']),
      _E('Roll Over', [
        'Pilates',
        'Mat Pilates',
        'Core',
        'Lower Back',
        'Flexibility',
      ]),
      _E('Single Leg Circle', [
        'Pilates',
        'Mat Pilates',
        'Hip Flexors',
        'Core',
        'Mobility',
      ]),
      _E('Rolling Like a Ball', [
        'Pilates',
        'Mat Pilates',
        'Core',
        'Lower Back',
        'Massage',
      ]),
      _E('Single Leg Stretch', [
        'Pilates',
        'Mat Pilates',
        'Core',
        'Abs',
        'Hip Flexors',
      ]),
      _E('Double Leg Stretch', [
        'Pilates',
        'Mat Pilates',
        'Core',
        'Abs',
        'Arms',
      ]),
      _E('Scissors', ['Pilates', 'Mat Pilates', 'Core', 'Abs', 'Hip Flexors']),
      _E('Lower Lift', ['Pilates', 'Mat Pilates', 'Core', 'Abs', 'Lower Body']),
      _E('Criss Cross', ['Pilates', 'Mat Pilates', 'Core', 'Obliques', 'Abs']),
      _E('Swan Dive', [
        'Pilates',
        'Mat Pilates',
        'Lower Back',
        'Glutes',
        'Flexibility',
      ]),
      _E('Single Leg Kick', [
        'Pilates',
        'Mat Pilates',
        'Hamstrings',
        'Glutes',
        'Lower Back',
      ]),
      _E('Double Leg Kick', [
        'Pilates',
        'Mat Pilates',
        'Hamstrings',
        'Glutes',
        'Chest',
      ]),
      _E('Side Kick', [
        'Pilates',
        'Mat Pilates',
        'Abductors',
        'Glutes',
        'Core',
      ]),
      _E('Leg Pull Front', [
        'Pilates',
        'Mat Pilates',
        'Core',
        'Glutes',
        'Stability',
      ]),
      _E('Teaser', ['Pilates', 'Mat Pilates', 'Core', 'Abs', 'Hip Flexors']),
      _E('Spine Stretch Forward', [
        'Pilates',
        'Mat Pilates',
        'Lower Back',
        'Hamstrings',
        'Flexibility',
      ]),
      _E('Saw', [
        'Pilates',
        'Mat Pilates',
        'Obliques',
        'Hamstrings',
        'Flexibility',
      ]),
      _E('Neck Roll', [
        'Pilates',
        'Reformer Pilates',
        'Flexibility',
        'Mobility',
        'Upper Traps',
      ]),
      _E('Chest Expansion', [
        'Pilates',
        'Reformer Pilates',
        'Chest',
        'Rear Delts',
        'Breathing',
      ]),

      // ── STRETCHING ─────────────────────────────────────────────────────
      _E('Standing Quad Stretch', [
        'Stretching',
        'Static Stretch',
        'Quadriceps',
        'Flexibility',
        'Mobility',
      ]),
      _E('Standing Hamstring Stretch', [
        'Stretching',
        'Static Stretch',
        'Hamstrings',
        'Flexibility',
      ]),
      _E('Seated Hamstring Stretch', [
        'Stretching',
        'Static Stretch',
        'Hamstrings',
        'Lower Back',
      ]),
      _E('Hip Flexor Stretch', [
        'Stretching',
        'Static Stretch',
        'Hip Flexors',
        'Flexibility',
        'Mobility',
      ]),
      _E('Piriformis Stretch', [
        'Stretching',
        'Static Stretch',
        'Glutes',
        'Hip Flexors',
        'Mobility',
      ]),
      _E('Butterfly Stretch', [
        'Stretching',
        'Static Stretch',
        'Adductors',
        'Hip Flexors',
        'Flexibility',
      ]),
      _E('Figure 4 Stretch', [
        'Stretching',
        'Static Stretch',
        'Glutes',
        'Hip Flexors',
        'Mobility',
      ]),
      _E('Chest Stretch', [
        'Stretching',
        'Static Stretch',
        'Chest',
        'Front Delts',
        'Flexibility',
      ]),
      _E('Doorway Chest Stretch', [
        'Stretching',
        'Static Stretch',
        'Chest',
        'Front Delts',
      ]),
      _E('Triceps Stretch', [
        'Stretching',
        'Static Stretch',
        'Triceps',
        'Flexibility',
      ]),
      _E('Cross-Body Shoulder Stretch', [
        'Stretching',
        'Static Stretch',
        'Rear Delts',
        'Shoulders',
      ]),
      _E('Sleeper Stretch', [
        'Stretching',
        'Static Stretch',
        'Rotator Cuff',
        'Mobility',
        'Rehabilitation',
      ]),
      _E('Lat Stretch', [
        'Stretching',
        'Static Stretch',
        'Lats',
        'Flexibility',
      ]),
      _E('Cat-Cow', [
        'Stretching',
        'Dynamic Stretch',
        'Lower Back',
        'Mobility',
        'Rehabilitation',
      ]),
      _E('World\'s Greatest Stretch', [
        'Stretching',
        'Dynamic Stretch',
        'Full Body',
        'Mobility',
        'Hip Flexors',
      ]),
      _E('Thoracic Rotation', [
        'Stretching',
        'Dynamic Stretch',
        'Upper Back',
        'Mobility',
        'Rehabilitation',
      ]),
      _E('Hip Circle', [
        'Stretching',
        'Dynamic Stretch',
        'Hip Flexors',
        'Mobility',
        'Glutes',
      ]),
      _E('Ankle Circle', [
        'Stretching',
        'Dynamic Stretch',
        'Calves',
        'Mobility',
        'Flexibility',
      ]),
      _E('Shoulder Circle', [
        'Stretching',
        'Dynamic Stretch',
        'Shoulders',
        'Mobility',
        'Rehabilitation',
      ]),
      _E('Neck Stretch', [
        'Stretching',
        'Static Stretch',
        'Upper Traps',
        'Flexibility',
        'Mobility',
      ]),
      _E('Wrist Stretch', [
        'Stretching',
        'Static Stretch',
        'Forearms',
        'Mobility',
        'Rehabilitation',
      ]),
      _E('Calf Stretch', [
        'Stretching',
        'Static Stretch',
        'Calves',
        'Flexibility',
        'Mobility',
      ]),
      _E('IT Band Stretch', [
        'Stretching',
        'Static Stretch',
        'Abductors',
        'Flexibility',
        'Rehabilitation',
      ]),
      _E('Foam Roll Quads', [
        'Stretching',
        'Foam Rolling',
        'Quadriceps',
        'Mobility',
        'Recovery',
      ]),
      _E('Foam Roll IT Band', [
        'Stretching',
        'Foam Rolling',
        'Abductors',
        'Mobility',
        'Recovery',
      ]),
      _E('Foam Roll Hamstrings', [
        'Stretching',
        'Foam Rolling',
        'Hamstrings',
        'Mobility',
        'Recovery',
      ]),
      _E('Foam Roll Calves', [
        'Stretching',
        'Foam Rolling',
        'Calves',
        'Mobility',
        'Recovery',
      ]),
      _E('Foam Roll Upper Back', [
        'Stretching',
        'Foam Rolling',
        'Upper Traps',
        'Rhomboids',
        'Mobility',
      ]),
      _E('Foam Roll Lats', [
        'Stretching',
        'Foam Rolling',
        'Lats',
        'Mobility',
        'Recovery',
      ]),
      _E('Foam Roll Glutes', [
        'Stretching',
        'Foam Rolling',
        'Glutes',
        'Mobility',
        'Recovery',
      ]),
      _E('PNF Hamstring Stretch', [
        'Stretching',
        'PNF Stretch',
        'Hamstrings',
        'Flexibility',
        'Rehabilitation',
      ]),
      _E('PNF Hip Flexor Stretch', [
        'Stretching',
        'PNF Stretch',
        'Hip Flexors',
        'Flexibility',
        'Rehabilitation',
      ]),
      _E('Scorpion Stretch', [
        'Stretching',
        'Dynamic Stretch',
        'Lower Back',
        'Hip Flexors',
        'Mobility',
      ]),
      _E('Inchworm', [
        'Stretching',
        'Dynamic Stretch',
        'Hamstrings',
        'Lower Back',
        'Full Body',
      ]),
      _E('Ankle Mobility Drill', [
        'Stretching',
        'Dynamic Stretch',
        'Calves',
        'Mobility',
        'Rehabilitation',
      ]),
      _E('90/90 Hip Stretch', [
        'Stretching',
        'Static Stretch',
        'Hip Flexors',
        'Glutes',
        'Adductors',
        'Mobility',
      ]),
      _E('Couch Stretch', [
        'Stretching',
        'Static Stretch',
        'Quadriceps',
        'Hip Flexors',
        'Mobility',
      ]),
      _E('Thoracic Open Books', [
        'Stretching',
        'Dynamic Stretch',
        'Upper Back',
        'Mobility',
      ]),
      _E('Ankle Dorsiflexion Rocks', [
        'Stretching',
        'Dynamic Stretch',
        'Calves',
        'Mobility',
      ]),
      _E('Deep Squat Hold', [
        'Stretching',
        'Static Stretch',
        'Mobility',
        'Hip Flexors',
      ]),
      _E('Mobility Flow', [
        'Stretching',
        'Dynamic Stretch',
        'Full Body',
        'Mobility',
      ]),
      _E('Cossack Squat', [
        'Stretching',
        'Dynamic Stretch',
        'Adductors',
        'Mobility',
        'Calisthenics',
      ]),

      // ── FUNCTIONAL / SPORT ─────────────────────────────────────────────
      _E('Box Step-Up', [
        'Functional',
        'Lower Body',
        'Quadriceps',
        'Glutes',
        'Sport',
      ]),
      _E('Lateral Box Jump', [
        'Functional',
        'Plyometric',
        'Lower Body',
        'Abductors',
        'Sport',
      ]),
      _E('Cone Drill', ['Functional', 'Agility', 'Sport', 'Cardio', 'HIIT']),
      _E('Medicine Ball Slam', [
        'Functional',
        'Core',
        'Abs',
        'Full Body',
        'HIIT',
      ]),
      _E('Medicine Ball Throw', [
        'Functional',
        'Core',
        'Full Body',
        'Power Yoga',
        'Sport',
      ]),
      _E('Medicine Ball Rotational Throw', [
        'Functional',
        'Core',
        'Obliques',
        'Sport',
        'Full Body',
      ]),
      _E('Band Squat Walk', [
        'Functional',
        'Glutes',
        'Abductors',
        'Resistance Bands',
        'Rehabilitation',
      ]),
      _E('Band Pull-Through', [
        'Functional',
        'Glutes',
        'Hamstrings',
        'Resistance Bands',
      ]),
      _E('Band Face Pull', [
        'Functional',
        'Rear Delts',
        'Rotator Cuff',
        'Resistance Bands',
      ]),
      _E('Band Chest Press', [
        'Functional',
        'Chest',
        'Triceps',
        'Resistance Bands',
      ]),
      _E('Band Row', ['Functional', 'Back', 'Biceps', 'Resistance Bands']),
      _E('Band Lateral Walk', [
        'Functional',
        'Glutes',
        'Abductors',
        'Resistance Bands',
        'Rehabilitation',
      ]),
      _E('Farmers Walk', [
        'Functional',
        'Grip',
        'Forearms',
        'Traps',
        'Full Body',
        'Strength',
      ]),
      _E('Sandbag Carry', ['Functional', 'Full Body', 'Core', 'Strength']),
      _E('Tire Flip', [
        'Functional',
        'Full Body',
        'Glutes',
        'Lower Back',
        'Strength',
        'CrossFit',
      ]),
      _E('Battle Rope Waves', [
        'Functional',
        'Shoulders',
        'Arms',
        'Cardio',
        'HIIT',
      ]),
      _E('Battle Rope Slams', [
        'Functional',
        'Core',
        'Shoulders',
        'Cardio',
        'HIIT',
      ]),

      // ── CLASSIC PROGRAM ADDITIONS ────────────────────────────────────
      _E('Barbell Floor Press', [
        'Chest',
        'Triceps',
        'Front Delts',
        'Strength',
        'Powerlifting',
      ]),
      _E('Clean and Press', [
        'Olympic Lifting',
        'Full Body',
        'Shoulders',
        'Strength',
      ]),
      _E('Reverse Hyperextension', [
        'Lower Back',
        'Glutes',
        'Hamstrings',
        'Rehabilitation',
        'Strength',
      ]),
      _E('Hip Abduction Machine', [
        'Lower Body',
        'Abductors',
        'Glutes',
        'Bodybuilding',
        'Rehabilitation',
      ]),
      _E('Side Press', [
        'Shoulders',
        'Side Delts',
        'Triceps',
        'Core',
        'Strength',
      ]),
      _E('California Press', [
        'Chest',
        'Triceps',
        'Strength',
        'Bodybuilding',
      ]),
      _E('High Cable Row', [
        'Back',
        'Rear Delts',
        'Rhomboids',
        'Upper Traps',
        'Bodybuilding',
      ]),
      _E('Single-Arm Lat Pulldown', [
        'Back',
        'Lats',
        'Biceps',
        'Bodybuilding',
      ]),
      _E('Weighted Crunch', [
        'Core',
        'Abs',
        'Bodybuilding',
      ]),
      _E('Wrist Roller', [
        'Arms',
        'Forearms',
        'Grip',
        'Strength',
      ]),
      _E('Incline Cable Fly', [
        'Chest',
        'Upper Chest',
        'Hypertrophy',
        'Bodybuilding',
      ]),
      _E('EZ Bar Skull Crusher', [
        'Arms',
        'Triceps',
        'Bodybuilding',
        'Hypertrophy',
      ]),
    ];

    for (final def in d) {
      final formattedName = Helpers.formatExerciseName(def.name);
      final ex = ExerciseDefinition(name: formattedName, tags: def.tags);
      await _storage.saveExercise(ex);
    }

    // Merge all exercise tags into global tag list
    final tagSet = <String>{..._storage.getTags()};
    for (final def in d) {
      tagSet.addAll(def.tags);
    }
    await _storage.saveTags(tagSet.toList()..sort());
  }
}

class _E {
  final String name;
  final List<String> tags;
  _E(this.name, this.tags);
}
